spring:
  config:
    import: "classpath:env.properties"
  datasource:
    url: "jdbc:postgresql://localhost:5432/${POSTGRES_DB}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true